### ISSUE TITLE
Create a CLI interface

### ISSUE THREAD

**Issue by gajus** [gajus/pg-formatter#1]
Create a CLI interface.

* Must allow to use all configurations available to the Node.js API.
* Must use https://github.com/yargs/yargs.

**Comment by paulmelnikow** [comment]
Hi! I rolled my own CLI for a project. I'd be happy to work on this.

Could the configuration options be set using something like [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)? It's easier to maintain in this repo than a bunch of CLI flags, and arguably more convenient for users to specify.

**Comment by gajus** [comment]
For consistency, I use https://www.npmjs.com/package/yargs in all my open-source projects. It looks interchangeable with cosmiconfig.

**Comment by paulmelnikow** [comment]
I don't think yargs handles config files, only command-line arguments, so what I'm suggesting is using them in combination. The CLI flags could handle things like the filenames, and maybe `anonymize` which might be on or off for different invocations, while the more extensive and expressive part of the config, like which formatting options to use, could live in the config file.

**Comment by karlhorky** [comment]
`yargs` could be integrated with `cosmiconfig` using `yargs.config()` or similar (see [saffron](https://github.com/darkobits/saffron) for an example)

**Comment by paulmelnikow** [comment]
Interesting. I've never used any of those libraries so it might be a lot to dig through. Though I'm game to give it a shot.

**Comment by phiresky** [comment]
Just for reference, here's what I currently use:

```ts
import { format } from "pg-formatter";
import * as fs from "fs";
const files = process.argv.slice(2);
const fix = !!process.env.fix;

const errors: string[] = [];
for (const file of files) {
	const content = fs.readFileSync(file, "utf8");
	// console.time("checking file " + file);
	const content2 = format(content, {
		keywordCase: "lowercase",
		noGrouping: true,
		tabs: false // because pasting tabs into psql prompt causes autocomplete
	});

	// console.timeEnd("checking file " + file);
	if (content !== content2) {
		if (fix) fs.writeFileSync(file, content2);
		else errors.push(file);
	}
}

if (errors.length > 0) {
	console.error("The following SQL files are not formatted. Please use `fix=1 ts-node check-pg-format.ts` to fix.");
	console.error(errors.join("\n"));
	process.exit(1);
}
```

It's not general enough to make a PR, but works for me.

I run this in CI in parallel using:

`git ls-files '*.sql' | xargs -n1 -P8 yarn ts-node --transpile-only util/check-pg-format.ts`

It can fix all by prefixing with `fix=1`
