### ISSUE TITLE
Reading configuration from rcfile (`.pg_format`)

### ISSUE THREAD

**Issue by amureki** [gajus/pg-formatter#11]
Greetings @gajus !

Thank you for a great package, I started using it in one of my projects, it is quite handy.

I am wondering if reading config from `.pg_format` works, can't find the logic for it after briefly skimming the code.

So, what I was trying to do - adding a small config, like this:

```
no-extra-line=1
```

running `pg_format` with this config works, but `pg-formatter` seems to ignore it.

I also did not find `-L | --no-extra-line` param in CLI here.
I am happy to provide a patch to add this one, if that'd be the way to go.

Best,
Rust

**Comment by ssukienn** [comment]
It is not working as this lib is using 4.4 version which does not yet have that. @gajus would it be possible to bump the `pg_formatter` binary in `package.json`?

**Comment by gajus** [comment]
We are now on v5.5

https://github.com/gajus/pg-formatter/blob/d0470269205dc69277aa4c83e612bfa1a50b6526/bin/postinstall-script.js#L10
