### ISSUE TITLE
Can this project use in the browser, e.g. Chrome、Safari？

### ISSUE THREAD

**Issue by cag2050** [gajus/pg-formatter#2]
Can this project use in the browser, e.g. Chrome、Safari？

**Comment by gajus** [comment]
Sure.

**Comment by cag2050** [comment]
1. When use pg-formatter(https://github.com/gajus/pg-formatter) in project built from vue-cli(https://github.com/vuejs/vue-cli), get error, I think pg-formatter using node api, so pg-formatter cann't use in browser environment.
2. The project demo: https://github.com/cag2050/pg-formatter_demo
