### ISSUE TITLE
Post-install script don't work on Windows 

### ISSUE THREAD

**Issue by npdev453** [gajus/pg-formatter#27]
`rm,` `tar` and other commands can be not found.

Any workaround? Broke npm install totally. Also when this package inluded as dependency.

**Comment by gajus** [comment]
PRs welcome

**Comment by npdev453** [comment]
@gajus 
https://github.com/gajus/pg-formatter/pull/28

**Comment by npdev453** [comment]
Also I think maybe this package should be published in registry with @darold pgFormatter library inlcuded inside?
Is it posible by pg license? Or bad practice?
