### ISSUE TITLE
update to 4.4?

### ISSUE THREAD

**Issue by phiresky** [gajus/pg-formatter#6]
Currently, pg_format 4.1 seems to be bundled. could you update it to current?

**Comment by gajus** [comment]
PR is welcome.

**Comment by phiresky** [comment]
i think there's no code to change, it seems like the pg_format is actually updated in a script, so it should only be `yarn build` and `yarn publish` :)

**Comment by phiresky** [comment]
It seems to fetch current tarball
```
curl -LkSs http://github.com/darold/pgFormatter/tarball/master/
```

and the result of that is not committed in the repo, so i don't think i can make a pr.

let me know if i can do anything else?

**Comment by phiresky** [comment]
@gajus please let me know if you plan on updating it, or if i can help in any way. otherwise i'll fork it at some point

edit: nevermind, sorry, i see you pushed a new version that fixed this automatically
